services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: testing
      POSTGRES_DB: test
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
