services:

  bot:
    ports:
      - "3000:80"
    volumes:
      - ".:/usr/src"
    env_file:
      - .env.bot.dev
    command: sh -c "npx prisma migrate deploy && yarn start:force"
    depends_on:
      db:
        condition: service_healthy
        restart: true
      redis:
        condition: service_started


  redis:
    image: redis:alpine
    restart: always

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: container
      POSTGRES_DB: onuw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
